#pragma once
enum KEYS {ESC,RIGHT, LEFT, DOWN}; //объявление клавиш
bool draw = true;// видимость фигуры
bool done=false;
int  dir=DOWN;
const int maxDragon = 8;	
int image_width = 0, image_height = 0;
ALLEGRO_DISPLAY*display = NULL;
ALLEGRO_EVENT_QUEUE*event_queue = NULL;
ALLEGRO_FONT *font = NULL;
ALLEGRO_FONT *font_menu = NULL;
ALLEGRO_TIMER *timer = NULL;
ALLEGRO_BITMAP *image = NULL;
ALLEGRO_BITMAP *Dragon = NULL;
ALLEGRO_BITMAP *Dragon_L_gold = NULL;
ALLEGRO_BITMAP *Grey_dragon_L = NULL;
ALLEGRO_BITMAP *Bomb = NULL;
ALLEGRO_BITMAP *Dragon_R = NULL;
ALLEGRO_BITMAP *Gold_dragon=NULL;
ALLEGRO_BITMAP *knight_go_R=NULL;
ALLEGRO_BITMAP *knight_go_L = NULL;
ALLEGRO_BITMAP*knightstan = NULL;
ALLEGRO_BITMAP*crocodile_R = NULL;
ALLEGRO_BITMAP*Ogr_L = NULL;
ALLEGRO_BITMAP *Die = NULL;
ALLEGRO_BITMAP *button1 = NULL;
ALLEGRO_BITMAP*teleport = NULL;
bool image_img = false;
bool out = false;
bool die = false;
bool exit_user = false;
int curframe = 0;
int framecount = 0;
int i = 0;
const int framdelay = 7;
const int framewidth = 128, frameheiht = 128;
const int framewidth_bomb = 64, frameheiht_bomb = 64;
const int fps = 60;
int count = 0, mana = 800;
const int width = 1600, height = 900;
 int x = width / 2, y = height / 2;
 int x_pos = 0, y_pos = 0;
int x_dragon = 600,  y_dragon = 400;
int x_gold_dragon = 300, y_gold_dragon = 300;
int x_dragon_R = 1000, y_dragon_R = 100;
int  x_bomb = 1000, y_bomb = 120;
int  x_bomb2 = 600, y_bomb2 = 400;
int  x_bomb3 = 300, y_bomb3= 200;
int  x_bomb4 = 1300, y_bomb4 = 200;
int x_croco_R = 500, y_croco_R = 650;
int x_knight = 10, y_knight = 650;
const int R = 40;
int x_ogr = 2300, y_ogr = 650;
int x_grey_dragon_L = -600, y_grey_dragon_L = 650;
